- bench.mojo
- numojo/__init__.mojo
- numojo/_math_funcs.mojo
- numojo/arithmetic.mojo
- numojo/check.mojo
- numojo/comparison.mojo
- numojo/traits/backend.mojo
- numojo/traits/tensor_traits.mojo
- numojo/trig.mojo
Add interchangeable backends for basic math functions. Naive uses loops, Vectorized uses SIMD vectorization, Parallel uses parallelization(and contains the code for ParralelizedVectorized which was always slower than either Parrallelized or Vectorized). Vectorized is the default, and the backend can be passed as a parameter to each function.
> Backend experimentation

- bench.mojo
- numojo/_math_funcs.mojo
- numojo/arithmetic.mojo
- numojo/check.mojo
- numojo/comparison.mojo
Update to Mojo 24.4.
all instances of `.data()` are now `.unsafe_ptr`
abs, trunc, floor, ceil, and round are now tabs, ttrunc, tfloor, tceil because mojo is not seeing the overload even when called explicitly from Numojo.
Depricated:
* reciprocal
* is_even
* is_odd
* is_power_of_2
Weirdness:
* Benchmarking doesn't seem to work the same way anymore on the memory side, so there are segfaults when the bench.mojo file is run. I'm not sure why, I think it may have something to do with unsafe pointer conversion. Code otherwise works when not benchmarked.
> 24.4 Update

- numojo/_math_funcs.mojo
Realized I was using the testing assert instead (at the time a new feature) and that it does not correctly raise errors. Replaced with normal raise Error syntax.
> Fixed error raising in dimension matching

- numojo/core/_array_funcs.mojo
- numojo/core/ndarray.mojo
- numojo/math/_math_funcs.mojo
- numojo/math/arithmetic.mojo
- numojo/math/check.mojo
- numojo/math/statistics/cumulative_reduce.mojo
- numojo/math/statistics/stats.mojo
Changed:
* All cumulative operations are now prefixed with cum example cumsum, to distinguish between cumulative and on axis.
* Moved most of the dunder math to _array_func implementations (the exception being pow).
Added:
* all and any functions to check currently require bool DType (we need to discuss applying truthiness to array members at some point)
* The following methods were implemented for NDArray cumprod, cumsum, prod, sum, and mean(both with and without axis).
> Added doc strings, all, any, added some functionality to ndarray usinexisting stuff

- numojo/core/ndarray_utils.mojo
- numojo/math/statistics/stats.mojo
The current prod function is not correct because it init an ndarray of zeros. Then the products will always be zeros. This pull request fix this.
Boundary check to enable _traverse_iterative to use store function without crash.
> prod function always generates zeros

- numojo/core/ndarray.mojo
- numojo/core/utility_funcs.mojo
- numojo/math/linalg/matmul.mojo
- numojo/math/statistics/stats.mojo
Add stats function `sumall`, `prodall`, `meanall` which return a scalar of all items in an array.
Set the default axis of `sum`, `prod`, `mean` to `0`.
Compared to `matmul_parallelized`, this function increase the size of the SIMD vector from the default width to 16. The purpose is to increase the performance via SIMD. The function reduces the execution time by ~50% compared to `matmul_parallelized` and `matmul_tiled_unrolled_parallelized` for large matrices.
Example: two 1000x1000 matrices, 100 times:
```
==================================================
Matmul paralelled CxC
0.13595043000000001 s
[[      -23.483741841786355     -15.701597076540736     26.473091851878582      ...    -31.718022704728931      1.6964271388761831      28.632800765314453      ]
[      -43.233593257424936 …
```
> Add stats function sumall, prodall, meanall. Improve performance of matmul function

- numojo/core/ndarray.mojo
Implement the `Sized` trait to allow `len()` function.
Implement the `__iter__` method and struct `_NDArrayIter` to iterate over the items in an ndarray.
```mojo
get(4, 4)
fn get(m:Int, n:Int) raises:
var raw = List[Int32]()
for _i in range(m*n):
raw.append(random.randn_float64() * 10)
var Ac = NDArray(data=raw, shape=List[Int](m,n), order="C")
for i in Ac:
print(i, end=" ")
print(Ac)
print(str("=") * 50)
```
Output:
```console
-12 16 13 -9 -16 0 0 -2 5 5 7 -9 -5 1 -3 17 
[[      -12     16      13      -9      ]
[      -16     0       0       -2      ]
[      5       5       7       -9      ]
[      -5      1       -3      17      ]]
Shape: [4, 4]  DType: int32
```
> Implement the __iter__ method to allow an iterator

- numojo/core/ndarray.mojo
- numojo/core/sort.mojo
Add bubble sort and quick sort in `numojo.core.sort` module. Implement the `sort` method using the quick sort algorithm. 
The location of the module is similar to the Numpy (`numpy._core.npysort`).
There is also a `binary_sort` function in the `numojo.math.statistics.cumulative_reduce`. I personally prefer a standalone `sort` module because the sorting functions are quite essential. Let's keep it an open discussion.
Test with an array of 10000 Float64 numbers, 1000 times.
```
Original array
[[      -1.2397359036589188     1.6120094337313993      1.3828016699156287      ...     -0.96682603166308989    -1.2589781838685108     -1.2540323302923684       ]]
Shape: [1, 10000]  DType: float64
==================================================
Binary sort
0.109690972 s
[[      -3.9278628912283353 …
```
> Add bubble sort and quick sort

- numojo/math/__init__.mojo
- numojo/math/linalg/matmul.mojo
Remove matmul_parallelized_simd as it is the same with the matmul_parallelized after introducing a nelt of 16. Updated the docstring.
Import all functions for the statistics and matmul modules.
> [lib] Remove matmul_parallelized_simd as it is the same with the matmul_parallelized

- numojo/core/ndarray.mojo
- numojo/core/ndarray_utils.mojo
Update `to_numpy` function so that multiple data types are allowed.
Example:
```
from python import Python
var array = nm.NDArray[nm.i32](1000,1000,random=True)
print(array.to_numpy())
```
float64:
```
[[0.085  0.8916 0.1897 ... 0.5549 0.2582 0.0078]
[0.8286 0.6087 0.1889 ... 0.8907 0.6361 0.82  ]
[0.6088 0.0533 0.7494 ... 0.0336 0.7792 0.7019]
...
[0.7376 0.4745 0.6004 ... 0.1094 0.8473 0.231 ]
[0.3293 0.7703 0.4481 ... 0.1036 0.252  0.1913]
[0.8816 0.6159 0.8896 ... 0.5805 0.7877 0.0112]]
```
int32:
```
[[ 1015961569 -1622847108  2029044002 ...  -454831891  1704168191
1437546358]
[ -520992968 -1055649167  -126675237 ...   -67502823 -1586034558
-316907984]
[-1275429598 -1923702087   133396804 ... -1838852486   688436754
-1148766235]
...
[  826482507 …
```
> Update `to_numpy` function so that multiple data types are allowed.

- numojo/core/ndarray.mojo
- numojo/math/linalg/matmul.mojo
Implement the `matmul` method using `matmul_parallelized` function. This allows the use of @ operator:
```
A @ B
```
> Implement the `matmul` method using `matmul_parallelized` function.

- numojo/core/ndarray.mojo
Currently, the `__str__` method of `NDArray` adds an extra `\n` at the end of the string. This causes an extra line to be printed when `print(array)` is used. This PR fixes this.
> [lib] Remove extra line when print array

- numojo/core/sort.mojo
- tests/argsort.mojo
Implement the `argsort` function. Add a test file.
Test results:
```console
[       0.085032448717433665    0.89161127730485756     0.18968977189964392     0.39800838814628897     0.74351245153226475     0.56038992815200594     ]
Shape: [6]  DType: float64
[       0       2       3       5       4       1       ]
Shape: [6]  DType: index
0.000174 s
==============================
[       11198796        2124991490      170454577       ...     1417941715      43647677        -248010538      ]
Shape: [12]  DType: int32
[       7       11      4       ...     5       9       1       ]
Shape: [12]  DType: index
7.8999999999999996e-05 s
==============================
[       0.54427280173529258     0.093629911904999585    0.43225952539313756     ...     0.34496925357704927 …
```
> [lib] Implement the `argsort` functionality

- numojo/core/ndarray.mojo
Check whether two ndarrays are equal.
The ndarrays are equal if:
(1) The shapes of the ndarrays are the same.
(2) The items of the ndarrays are equal.
> [lib] Update `__eq__` method of NDArray.

- numojo/core/ndarray.mojo
Implement the `__repr__` method that computes the "official" string representation of NDArray.
An example is:
```mojo
var A = NDArray[DType.int8](List[Scalar[DType.int8]](14,97,-59,-4,112,), shape=List[Int](5,))
print(repr(A))
```
It prints what can be used to construct the array itself:
```console
NDArray[DType.int8](List[Scalar[DType.int8]](14,97,-59,-4,112,), shape=List[Int](5,))
```
> [lib] Implement the `__repr__` method.

- README.MD
- Roadmap.md
- numojo/__init__.mojo
- numojo/core/ndarray.mojo
- numojo/core/ndarray_utils.mojo
- numojo/math/arithmetic.mojo
- numojo/math/check.mojo
- numojo/math/comparison.mojo
- numojo/math/interpolate.mojo
- numojo/math/linalg/linalg.mojo
- numojo/math/math_funcs.mojo
- numojo/math/statistics/cumulative_reduce.mojo
- numojo/math/statistics/stats.mojo
- numojo/math/trig.mojo
- numojo/traits/backend.mojo
All references to tensor type have been removed.  All of the math docstrings are correctly formatted if not perfectly written.
Core needs a lot of work for documentation still.
> Remove References to tensor and fix some doctrings

- numojo/core/ndarray.mojo
- tests/argsort.mojo
- tests/getitem.mojo
Related to Discussion #70 
- Use the `Variant[Slice, Int]` as the uniformed way to `__getitem__`. The `__getitem__` always returns an array.
- The previous `__getitem(self, idx: Int)` is renamed as `get_scalar`. It gets a scalar from the buffer.
- The previous `__getitem(self, *idices: Int)` is renamed as `at`, which always returns a scalar at the given coordinates.
Here are example when `A` is a vector, a matrix, and a 3d array. The behavior met our expectation: The number of dimension reduced equals to the number of integers as input.
```console
A is a matrix
[[      -128    -95     65      -11     ]
[      8       -72     -116    45      ]
[      45      111     -30     4       ]
[      84      -120    -115    7       ]]
2-D array  Shape: [4, 4]  DType: int8
A[0]
[       -128    -95 …
```
> [lib] `__getitem__` uniformed behavior + 0d-array + get item with indices

- numojo/core/datatypes.mojo
- numojo/core/ndarray.mojo
- numojo/core/ndarray_utils.mojo
- numojo/math/statistics/cumulative_reduce.mojo
- numojo/math/statistics/stats.mojo
- tests/stats.mojo
Add a bunch of docstrings and examples mainly for `math` module and two functions (`to_numpy` and `__getitem__` in the `core` module).
> [doc] Add a bunch of docstrings and examples mainly for `math` module

- numojo/core/ndarray.mojo
- numojo/core/sort.mojo
- numojo/math/arithmetic.mojo
- numojo/math/calculus/differentiation.mojo
- numojo/math/calculus/integral.mojo
- numojo/math/check.mojo
- numojo/math/interpolate.mojo
- numojo/math/linalg/linalg.mojo
- numojo/math/statistics/cumulative_reduce.mojo
I fixed all of the stuff in the package that is broken by the get and set item calls for NDArray. Except for interpolation, because that thing has like 200 get item calls and when I tried to make it work with ndarray singles it had the unable to infer parameter issue.
> Fix all the stuff that the new get and set methods broke

- numojo/core/ndarray.mojo
Update the `__int__` method to match the behavior of Numpy.
Similar to Numpy, only 0-D arrays or length-1 arrays can be converted to scalars.
Example:
```console
> var A = NDArray[dtype](6, random=True)
> print(int(A))
Unhandled exception caught during execution: Only 0-D arrays or length-1 arrays can be converted to scalars
mojo: error: execution exited with a non-zero result: 1
> var B = NDArray[dtype](1, 1, random=True)
> print(int(B))
14
```
> Update the `__int__` method to match the behavior of Numpy

- numojo/core/ndarray.mojo
- numojo/core/ndarray_utils.mojo
- numojo/math/statistics/cumulative_reduce.mojo
- tests/getitem.mojo
- tests/iter.mojo
The iterate will return the first dimensions instead of scalars.
```console
> var A = nm.NDArray[dtype](3, 3, random=True, order="F")
> print(A)
[[      14      -4      -48     ]
[      97      112     -40     ]
[      -59     -94     66      ]]
2-D array  Shape: [3, 3]  DType: int8
> for i in A:
>     print(i)  # Return rows
[       14      -4      -48     ]
1-D array  Shape: [3]  DType: int8
[       97      112     -40     ]
1-D array  Shape: [3]  DType: int8
[       -59     -94     66      ]
1-D array  Shape: [3]  DType: int8
```
Align the behavior of `item` with numpy.
Return the scalar at the coordinates.
If one index is given, get the i-th item of the array.
It first scans over the first row, even if it is a column-major array.
If more than one index is given, the length of the …
> [lib] Improve `iter` and `item` functions

- numojo/core/ndarray.mojo
- tests/array_from_string.mojo
Englighted by #80, I have implemented a new initialization of the NDArray directly from a string representation, which I found quite useful. 
NDArray initialization from string representation of an ndarray.
The shape can be inferred from the string representation.
The literals will be casted to the dtype of the NDArray.
Note:
StringLiteral is also allowed as input as it is coerced to String type before it is passed into the function.
Example:
```mojo
var A = nm.NDArray[DType.int8]("[[[1,2],[3,4]],[[5,6],[7,8]]]")
var B = nm.NDArray[DType.float16]("[[1,2,3,4],[5,6,7,8]]")
var C = nm.NDArray("[0.1, -2.3, 41.5, 19.29145, -199]")
var D = nm.NDArray[DType.int32]("[0.1, -2.3, 41.5, 19.29145, -199]")
print(A)
print(B)
print(C)
print(D)
```
The output goes as …
> [lib+test] NDArray initialization from string representation of an ndarray

- new_tests/README.md
- new_tests/test_array_creation.mojo
- new_tests/test_math.mojo
- new_tests/utils_for_test.mojo
- numojo/core/array_creation_routines.mojo
- numojo/math/calculus/differentiation.mojo
This update replaces in_dtype and out_dtype in functions where they were used with dtype. This was done because having two dtype options was confusing and the desired result was preventing Integer types from being used when those types are unsuitable. Additionally, I added constraints to the functions that cannot return ints (usually because the ability to represent values is exceeded) such that a compile-time error will occur if integral types are used in those functions.
This pull request also adds some basic tests and provides a basic framework to test correctness by comparing our results with numpy.
As a side note, this led me to discover that only the parallel version of matmul is correct.
> Type stuff and testing

- numojo/core/ndarray.mojo
Add the option to initialize a NDArray with random values between min and max values with the following syntax:
```mojo
var A = nm.NDArray[DType.float16](List[Int](2, 2), min=0.0, max=10.0)
print(A)
```
[Output]:
```console
[[	7.515625	8.25	]
[	7.53125	3.19140625	]]
2-D array  Shape: [2, 2]  DType: float16
```
> Add NDArray initialization with random values in an specified interval

- numojo/core/array_creation_routines.mojo
- numojo/core/ndarray.mojo
- numojo/core/ndarray_utils.mojo
- numojo/core/random.mojo
- numojo/math/calculus/differentiation.mojo
- numojo/math/linalg/solve.mojo
- numojo/math/statistics/cumulative_reduce.mojo
- test.mojo
- tests/test_array_creation.mojo
- tests/test_array_manipulation.mojo
- tests/test_bool_masks.mojo
- tests/test_constructors.mojo
- tests/test_math.mojo
- tests/test_random.mojo
- tests/test_slicing.mojo
- tests/test_sort.mojo
- The constructors that take `shape` and `fill` value as input return a unintialized array by default if a `fill` value is not provided.  
- The fill value operation is vectorized. 
- Removed `random` argument from NDArray constructors.
- Added `rand(*shape: Int, min: Scalar[dtype], max: Scalar[dtype])` and `rand(shape: List[Int], min: Scalar[dtype], max: Scalar[dtype])` for creating random arrays with random values within a range [min, max].
- Added `randn(*shape: Int, mean: Scalar[dtype], variance: Scalar[dtype])` and `rand(shape: List[Int], mean: Scalar[dtype], variance: Scalar[dtype])` for creating arrays with random values chosen from a normal distribution with given mean and variance. The name of this function could be changed to something else to remove any confusions. 
- Updated …
> Moving `random` constructors

- numojo/core/ndarray.mojo
- tests/test_math.mojo
Add `itemset` function to fill in a scalar at the certain coordinates of a ndarray.
It is similar to `numpy.ndarray.itemset`. It is better then `__setitem__`.
Now we have both `item` and `itemset` function to read and write a scalar into the array.
```mojo
var A = nm.zeros[nm.i16](3, 3)
print(A)
A.itemset(5, 256)
print(A)
A.itemset(List(1,1), 1024)
print(A)
```
> [Add] `itemset` function to fill in a scalar at the certain coordinates of a ndarray

- magic.lock
- numojo/core/array_creation_routines.mojo
- numojo/core/ndarray.mojo
- numojo/core/ndarray_utils.mojo
- numojo/core/random.mojo
- numojo/core/sort.mojo
- numojo/math/arithmetic.mojo
- numojo/math/calculus/integral.mojo
- numojo/math/linalg/matmul.mojo
- numojo/math/math_funcs.mojo
- numojo/math/statistics/cumulative_reduce.mojo
- test.mojo
- tests/test_math.mojo
- tests/utils_for_test.mojo
- Added `Formattable` trait and fixed the `print()` function. 
- Minor updates to things like `Slice`, `__setitem__`
- Commented out `VectorizedParallelizedNworkers` and it's corresponding tests since it's crashes the compiler. 
- All the Matmul functions result in Seg fault except for `matmul_naive`. Even then, the `matmul_naive` results are wrong when compared to numpy. 
- The `inv` and `solve` function in linalg module output wrong values such as Nan, Inf etc for some values.
> Updated numojo to mojo24.5

- numojo/math/linalg/matmul.mojo
- numojo/math/linalg/solver.mojo
- test.mojo
- tests/test_math.mojo
This PR is to solve the issue with `solve` and `inv` due to problems in paralellization.
For `solve`: Disable the parallelism and use normal loop approach for the moment until the issue is resolved.
For `inv`: The approach to calculate inverse is to solve the system `AB=I`, where `I` is an identity matrix, with the function `solve`. This is also what Numpy does.
For `matmul`: It seems to be related to ASAP destruction policy and can be resolved by using the variables after the paralellization.
> [fix] Fix the issues with `solve`, `inv`, and `matmul`

- numojo/core/array_creation_routines.mojo
- numojo/math/linalg/solver.mojo
- tests/test_array_creation.mojo
Solve the issue in parallelization for `solve`. This allows us to enable `parallelize` again for the solver.
> [fix] Solve the issue in parallelization for `solve`

- numojo/prelude.mojo
This idea comes from the Rust.
NuMojo comes a wide range of functions, types, and constants. If you manually import everything, it will make the header of the file too long. On the other hand, using `from numojo import *` would import a lot of functions that you never use and would pollute the naming space.
This module tries to find out a balance by providing a list of things that can be imported at one time. The list contains the functions or types that are the most essential for a user. 
You can use the following code to import them:
```mojo
from numojo.prelude import *
var array = NDArray[i32](shape=List[Int](2, 3))
print(array)
```
In this case `NDArray` and dtypes are automatically imported.
> [new] Add `prelude` module for better importing

- .github/workflows/run_tests.yaml
- .github/workflows/test_pre_commit.yaml
Github runner was having issues, so I am trying 22.04 since that is the version confirmed to work with Mojo.
> Switch github runner to ubuntu-22.04

- numojo/core/ndshape.mojo
- numojo/math/linalg/matmul.mojo
- numojo/prelude.mojo
- tests/test_math.mojo
The `matmul` returns wrong results for small matrices. The reason is that the initialization on the `C` is not filled with `0` but uninitilized.
This PR is a quick fix on this.
> [fix] Fix mistakes in `matmul` due to initialization of the zero matrix

- numojo/core/array_creation_routines.mojo
There is an error in `fromstring` that the negative signs are not read.
Now a valid numeric should start with a digit, a dot, or a hyhen.
> [fix] Fix an error in `fromstring` where the negative signs are not read.

- numojo/core/array_creation_routines.mojo
- numojo/core/array_manipulation_routines.mojo
- numojo/core/ndarray.mojo
- numojo/core/random.mojo
- numojo/core/sort.mojo
- numojo/core/utility.mojo
- numojo/io/files.mojo
- numojo/math/interpolate.mojo
- numojo/math/signal/signal.mojo
- numojo/math/statistics/stats.mojo
- test.mojo
- tests/test_random.mojo
The data buffer of `NDArray` is an `unsafepointer`. We should not expose it to the users. So it is renamed to `_buffer` with an underscore.
> [change] Rename the data buffer from `data` to `_buffer`

- numojo/core/array_creation_routines.mojo
- numojo/core/array_manipulation_routines.mojo
- numojo/core/mat/creation.mojo
- numojo/core/ndarray.mojo
- numojo/core/sort.mojo
- numojo/io/files.mojo
- numojo/math/interpolate.mojo
- numojo/math/linalg/matmul.mojo
- numojo/math/linalg/solver.mojo
- tests/test_array_creation.mojo
- tests/test_array_manipulation.mojo
- tests/test_constructors.mojo
It is related to discussion #90 and #110. Because `NDArray()` does not provide any hints on parameters, it is always nice to use functions in `array_creation_routine` to create arrays.
The array creation functions are unified in such a way:
- `NDAarray.__init__()` reads in `shape` information and initializes an empty ndarray.
- All other creation routines are implemented by the functions in the `array_creation_routine` module. For example, to create an array with filled value, the function `nm.full` should be used. To create an array from a list, the function `nm.array` should be used.
> [change] Unify the array creation functions

- numojo/core/ndarray.mojo
Add more detailed error messages. For example, when an index is out of boundary, the index and the size of the list will be printed. This provides more convenience in dubugging.
> [change] Add more detailed error messages

- numojo/core/__init__.mojo
- numojo/core/array_creation_routines.mojo
- numojo/core/array_manipulation_routines.mojo
- numojo/core/ndarray.mojo
- numojo/core/ndshape.mojo
- numojo/core/ndstride.mojo
- numojo/core/ndstrides.mojo
- numojo/core/random.mojo
- numojo/core/sort.mojo
- numojo/core/utility.mojo
- numojo/io/files.mojo
- numojo/mat/linalg.mojo
- numojo/mat/matrix.mojo
- numojo/math/check.mojo
- numojo/math/linalg/linalg.mojo
- numojo/math/linalg/matmul.mojo
- numojo/math/signal/signal.mojo
- numojo/math/statistics/stats.mojo
- test.mojo
- tests/test_constructors.mojo
Rename some attributes to be consistent with [numpy](https://numpy.org/doc/stable/reference/generated/numpy.ndarray.html)
- `ndlen`->`ndim`
- `ndshape`->`shape`
- `ndstride`->`strides`
- `stride`->`strides`
- `ndsize`->`size`
Make `size` an attribute instead of a method.
> [change] Rename some attributes and make `size` an attribute

- .github/workflows/test_pre_commit.yaml
- .gitignore
- .pre-commit-config.yaml
- magic.lock
- mojoproject.toml
- numojo/core/_math_funcs.mojo
- numojo/core/index.mojo
- numojo/core/ndarray.mojo
- numojo/core/ndshape.mojo
- numojo/core/ndstrides.mojo
- numojo/core/utility.mojo
- numojo/mat/matrix.mojo
- numojo/mat/sorting.mojo
- numojo/routines/constants.mojo
- numojo/routines/creation.mojo
- numojo/routines/manipulation.mojo
- numojo/routines/random.mojo
- numojo/routines/sorting.mojo
- numojo/science/interpolate.mojo
- numojo/traits/NDArrayTraits.mojo
- numojo/traits/backend.mojo
This PR update the code to accommodate Mojo v24.6, released on 17 December 2024. It fixes the problems and make all tests pass. Notably:
- `Slice.step` is now returning `Optional[int]`. Thus, it is fixed by using `Slice.step.else_to(1)`.
- `Formattable` is now renamed to `Writable` (same applies to `write_to` and `string.write`).
- `width` is now inferred from the SIMD's width. So this parameter must be removed when we call `UnSafePointer`'s `load` and `store` methods. Due to this, the function `fill_pointer`, which fill in a width of array with a scale, no longer work. It is replaced by copying with loop.
- `Lifetime` is renamed as `Origin` (same applies to the function `__origin_of`).
- `inout` is renamed as `mut`.
Moreover, I updated the pre-commit workflow, using `magic` instead of …
> [fix] Update the code to accommodate Mojo v24.6 (17 December 2024)

- .gitignore
- numojo/core/datatypes.mojo
- numojo/core/ndshape.mojo
- numojo/core/ndstrides.mojo
- numojo/routines/__init__.mojo
- numojo/routines/linalg/products.mojo
- numojo/routines/math/sums.mojo
- numojo/routines/random.mojo
- numojo/routines/statistics/averages.mojo
- numojo/science/signal.mojo
- tests/test_array_creation.mojo
- tests/test_math.mojo
- tests/test_matrix.mojo
- tests/test_random.mojo
- tests/test_signal.mojo
- tests/test_sort.mojo
- tests/utils_for_test.mojo
Update the `numojo.routines.math.sums.sum` function:
1. Merge `sumall` into `sum`. If no `axis` is given, then function returns a scalar, otherwise an array.
2. Fix un-initialization issue with `sum`.
3. Add test for `sum` for 3 axis's.
4. Remove `from time import now`.
5. Rename builtin `random` module as `builtin_random` during import, avoiding leaks in namespace.
6. Change `dtype` of `NDArrayShape` and `NDArrayStrides` to `DType.index` to ensure no overflow during casting.
> [fix] Update the `sum` function

- numojo/__init__.mojo
- numojo/core/ndarray.mojo
- numojo/routines/manipulation.mojo
- tests/test_array_manipulation.mojo
This PR updates the `transpose` function and allow:
(1) Arbitrary dimensions of arrays (>2).
(2) Arbitrary permutations of axes as extra argument. if `axes` is not given, then it is defaulted to the flipping of the axes.
An example of 4darray.
```mojo
A = nm.random.randn(2, 3, 4, 5)
nm.transpose(A) # transpose over axes = (3, 2, 1, 0)
nm.transpose(A, axes=List(1, 3, 0, 2)) # arbitrary axes
```
> [update ] `transpose` allow arbitrary dimensions and permutations of axes

- numojo/__init__.mojo
- numojo/core/ndarray.mojo
- numojo/core/utility.mojo
- numojo/routines/linalg/products.mojo
- numojo/routines/manipulation.mojo
- numojo/routines/sorting.mojo
- tests/test_array_creation.mojo
- tests/test_array_manipulation.mojo
- tests/test_bool_masks.mojo
- tests/test_math.mojo
- tests/test_slicing.mojo
- tests/test_sorting.mojo
I refined and fixed the functions `reshape` `resize` and methods `flatten` 'ravel` so that:
1. Refine the function `reshape` so that it is working on any dimensions and is working on both row-major and col-major. This also allows us to change the order with the code:
```mojo
A = nm.random.randn(Shape(2,3,4))
A.reshape(A.shape, "F"))
```
2. Add a new method `resize` that reshapes the array in-place. `reshape` method returns a copy of the array.
3. Refine the function `ravel` so that it allows to flatten the array by either row-major or col-major.
4. Update the method `flatten` which has the same behavior as `ravel`.
5. And two auxiliary functions that generate a list of integers given range, e.g., `[0,1,2,3]`.
6. Show order of the array during printing.
The functions are tested against …
> [update][manipulation routines] Refine functions `reshape`, `resize`, `flatten`, `ravel`

- mojoproject.toml
- numojo/__init__.mojo
- numojo/core/ndarray.mojo
- numojo/core/ndshape.mojo
- numojo/core/ndstrides.mojo
- numojo/core/utility.mojo
- numojo/routines/manipulation.mojo
- numojo/routines/math/__init__.mojo
- numojo/routines/math/products.mojo
- numojo/routines/math/sums.mojo
- numojo/routines/statistics/averages.mojo
- tests/test_math.mojo
This PR:
- Fixes `cumsum` and `cumprod` so it returns array instead of number.
- Allows `cumsum` and `cumprod` by any axis.
- Adds an auxiliary function in utility module `_traverse_buffer_according_to_shape_and_strides` that traverse array with shape and strides.
- Removes `mut` keyword from `NDArray.__add__`
- Adds auxiliary methods `_flip`, `_move_axis_to_end` for `NDArrayShape` and `NDArrayStrides`.
> [fix][math routines] Allow `cumsum` and `cumprod` by any axis

- numojo/core/ndarray.mojo
- numojo/routines/random.mojo
- tests/test_array_creation.mojo
- tests/test_array_indexing_and_slicing.mojo
- tests/test_array_methods.mojo
The methods `get` and `set` of `NDArray` does not check against big negative index values and this leads to overflows.
I fixed it by adding more boundary checks.
Moreover, (1) I renamed two private functions with prefix `_`. (2) I used `init_pointee_copy` for functions in `random` module to avoid unintended behaviors.
> [fix][ndarray] Fix overflow due to negative `index` argument for `get` and `set` of `NDArray`

- mojoproject.toml
- numojo/core/_array_funcs.mojo
- numojo/core/_math_funcs.mojo
- numojo/core/ndarray.mojo
- numojo/core/utility.mojo
- numojo/routines/linalg/products.mojo
- numojo/routines/linalg/solving.mojo
- numojo/routines/logic/contents.mojo
- numojo/routines/logic/truth.mojo
- numojo/routines/math/arithmetic.mojo
- numojo/routines/math/differences.mojo
- numojo/routines/math/extrema.mojo
- numojo/routines/searching.mojo
- numojo/routines/sorting.mojo
- numojo/routines/statistics/averages.mojo
- tests/test_array_indexing_and_slicing.mojo
1. Remove the property `coefficient` as it is not effectively in use but takes extra memory.
2. Update the `__len__` method to return the size of the 0-th dimension.
3. Make 'load' and 'store' methods safer by adding boundary checks. For unsafe uses, `A._buf.load` and `A._buf.store` would work.
4. `get` and `set` methods have similar behavior as `load` and `store`, i.e., getting values at certain index from the underlying buffer. So, just rename `get` and `set` as `load` and `store` to achieve consistency.
5. Some cleaning work for docstrings.
> [update][core] Update several methods of `NDArray` type

- numojo/core/ndarray.mojo
- numojo/core/utility.mojo
- numojo/mat/matrix.mojo
- numojo/routines/creation.mojo
- numojo/routines/manipulation.mojo
- numojo/routines/sorting.mojo
- Create `flags` property (a `Dict`) to store memory layout of the array (c-continuous, f-continuous, own data). This is the approach by `numpy`.
- Remove property `datatype`. The `dtype` can be retrieved simply by `a.dtype`.
- Refine the `__init__` overloads to match `numpy`'s order of arguments.
> [core][ndarray] `flags` replaces `order` property. Remove `datatype` property.

- numojo/routines/linalg/__init__.mojo
- numojo/routines/linalg/decompositions.mojo
- numojo/routines/linalg/norms.mojo
- tests/test_linalg.mojo
- Add `det` function in `numojo.routines.linalg.norms`.
- And auxiliary `partial_pivoting` function in `numojo.routines.linalg.decompositions`. This, combined with `lu_decomposition`, can be used as LUP decomposition.
> [routines][linalg] Add `det` function and auxiliary partial pilot

- numojo/mat/linalg.mojo
- tests/test_matrix.mojo
This pull request adds a Householder-based QR decomposition. I have added a test to verify that the resulting matrices Q and R have the properties:
- Q is orthonormal
- R is upper triangular
- A=Q*R
For improved performance on bigger matrices, adopting a blocked/tiled QR factorization and leveraging SIMD or parallelization would be beneficial.
> [matrix][linalg] Add Householder-based QR decomposition

- numojo/core/index.mojo
- numojo/core/ndarray.mojo
- numojo/core/ndstrides.mojo
- numojo/core/utility.mojo
- numojo/routines/creation.mojo
- Remove `offset` property from `Strides` type. `offset` is used when constructing a view/copy of array, but not a property of array or strides.
- Rename the underlying buffer of `Idx` type to `_buf`.
- Rename `_get_index` as `_get_offset` because it is *de facto* obtaining the offset (in item size) of the underlying buffer given indices and strides. Remove the overloads which reads in `Shape` because the result is not meaningful.
> [core][strides][Idx] Remove `offset` property from the `Strides` type and more

- numojo/core/ndarray.mojo
- numojo/core/ndshape.mojo
- numojo/core/ndstrides.mojo
Return view instead of copy for iterator of `NDArray`.
```mojo
>>> var a = nm.random.arange[nm.i8](2 * 3 * 4).reshape(nm.Shape(2, 3, 4))
>>> for i in a:
...     print(i)
[[      0       1       2       3       ]
[      4       5       6       7       ]
[      8       9       10      11      ]]
2-D array  Shape: [3, 4]  DType: int8  C-cont: True  F-cont: False  own data: False
[[      12      13      14      15      ]
[      16      17      18      19      ]
[      20      21      22      23      ]]
2-D array  Shape: [3, 4]  DType: int8  C-cont: True  F-cont: False  own data: False
```
> [ndarray][iterator] Return view instead of copy for iterator of `NDArray`

- .github/workflows/run_tests.yaml
- numojo/core/matrix.mojo
- numojo/core/ndarray.mojo
- numojo/core/utility.mojo
- numojo/routines/logic/truth.mojo
- numojo/routines/manipulation.mojo
- numojo/routines/math/extrema.mojo
- numojo/routines/math/products.mojo
- numojo/routines/math/rounding.mojo
- numojo/routines/math/sums.mojo
- numojo/routines/sorting.mojo
1. Update the underlying data buffer of `Matrix` type to `OwnData`, aligned with `NDArray`.
2. Introduce an internal function `_update_flags` that determines the C/F-CONTINUOUS information from strides and shape of the array.
3. The "continuous" information should also be determined by shape of array.
> [Matrix][NDArray] Change data buffer of `Matrix` to `OwnData` and better `flags`

- numojo/core/ndarray.mojo
- numojo/core/ndshape.mojo
- numojo/core/ndstrides.mojo
- numojo/routines/manipulation.mojo
This PR makes some updates to the `NDArrayShape` and `NDArrayStrides`.
1. Make `NDArrayShape` and `NDArrayStrides` `@register_passable` instead of `@register_passable("trivial")`.
Reason: This is to prevent implicit copy by reference. For example, before change, the following code is not what we want and is prone to mistakes.
```mojo
>>>var a = nm.NDArrayShape(1, 2, 3)
>>>var b = a
>>>b[0] = 10
>>>print(a)
```
After change, this is avoided.
```mojo
>>>var a = nm.NDArrayShape(1, 2, 3)
>>>var b = a
>>>b[0] = 10
>>>print(a)
```
2. Change the `size` property into `size_of_array` method for `NDArrayShape`.
Reason: The size information is only used when we want to know the size of array from the shape. If it is a property, it must be calculated at the initialization of the shape, causing …
> [shape] Update `NDArrayShape`, making `size` a method

- numojo/core/datatypes.mojo
- numojo/core/ndarray.mojo
This PR aims to improve the string presentation of ndarray.
Now there are three more arguments:
1. `separator` controls the symbols between items.
2. `padding` controls the symbols between items and brackets.
3. `items_to_display` controls number of items to print
Example:
```console
>>>var b = nm.arange[nm.i8](10, 46).reshape(Shape(6, 6))
>>>print(b._array_to_string(0, 0, ",", " ", items_to_display=4))
[[ 10,11,...,14,15 ]
[ 16,17,...,20,21 ]
...
[ 34,35,...,38,39 ]
[ 40,41,...,44,45 ]]
```
Now `str`, `repr`, and `write_to` are modified to show different things.
`str(array)` only print the items.
```console
[[      10      11      12      13      14      15       ]
[      16      17      18      19      20      21       ]
[      22      23      24      25      26      27       ]
[ …
```
> [ndarray] Better string presentation and print for `NDArray`

- numojo/core/item.mojo
- numojo/core/ndarray.mojo
[ndarray][nditer] Add `NDIter` struct to iterate items in `NDArray`
This struct is an iterator over items of `NDArray` according to the memory layout of the array or a manually input order.
This method creates an instance of `NDIter` iterator. There are two overloads. If no `order` argument is passed in, the iterator walks through the array according to its memory layout. If `order` argument is passed in, the iterator walks through the array according to this `order`.
See the following example code and note the difference.
```mojo
var a = nm.array[i8]("[[1, 2], [3, 4], [5, 6]]")
print(a)
for i in a.nditer():
print(i, end=" ")
print()
for i in a.nditer("C"):
print(i, end=" ")
print()
for i in a.nditer("F"):
print(i, end=" ")
print()
a = a.reshape(Shape(3, 2), order="F") …
```
> [ndarray][nditer] Add `NDIter` struct to iterate items in `NDArray` + add `copy` method

- numojo/core/complex/complex_ndarray.mojo
- numojo/core/ndarray.mojo
- numojo/routines/creation.mojo
- numojo/routines/io/formatting.mojo
As a follow-up of PR#190, this PR makes the width of formatting automatically adapted to the numbers to be printed.
Also fix a bug where values between 0 and -1 are not properly printed (the minus sign are not printed)
(For future: when the bug in the scientific formatting is fixed, the values can be formatted as scientific numbers if their length is over 14 letter.)
See the comparison with numpy:
```mojo
var a = nm.random.randn[f64](100, 100) * 1000
print(a)
print(a.to_numpy())
var b = nm.arange[i32](10000).reshape(Shape(100, 100))
print(b)
print(b.to_numpy())
```
```console
[[ -336.1702  -190.7101   300.1279 ...   509.2278   566.8533 -1450.7406]
[ -856.5637 -1204.5281  1192.1241 ...  1555.7254   314.0418  -764.8215]
[ -314.5754   607.5819  1085.7264 ...  1106.8583 …
```
> [formatting] Auto-adjusted width of formatted values during `print`

- numojo/core/ndarray.mojo
- numojo/routines/io/formatting.mojo
Follow-up on PR #191. Align the printing behavior with numpy.
1. Corrected scientific formatting on negative values and value smaller than 1.
2. Print in scientific format when `formatted_width > 14` or values are below 1.
Example of very large values:
```mojo
from numojo.prelude import *
a = nm.random.randn[f64](4, 4) * 100000000
print(a)
print(a.to_numpy())
```
```console
[[ 2.1172e+07 -1.6633e+08 -5.1568e+07 -1.6496e+08]
[ 1.6345e+06 -9.2600e+07 -7.0699e+07  9.9001e+07]
[ 2.2619e+07 -1.1670e+08 -3.3015e+07 -3.8808e+07]
[-1.1040e+08 -6.4122e+07  8.5955e+07  7.7721e+07]]
2D-array  Shape(4,4)  Strides(4,1)  DType: f64  C-cont: True  F-cont: False  own data: True
[[ 2.1172e+07 -1.6634e+08 -5.1569e+07 -1.6497e+08]
[ 1.6345e+06 -9.2601e+07 -7.0700e+07 …
```
> [io][formatting] Corrected scientific formatting and do this when `formatted_width > 14`

- .github/workflows/run_tests.yaml
- .github/workflows/test_pre_commit.yaml
- numojo/__init__.mojo
- numojo/core/matrix.mojo
- numojo/core/ndarray.mojo
- numojo/prelude.mojo
- numojo/routines/manipulation.mojo
- tests/routines/test_manipulation.mojo
Implements `broadcast_to()` for `NDArray`. Add tests.
It can broadcast an ndarray of any shape to any compatible shape. The data will be copied into the new array. An example goes as follows.
```mojo
from numojo.prelude import *
from python import Python
var np = Python.import_module("numpy")
var a = nm.random.rand(Shape(2, 3))
print(a)
print(nm.routines.manipulation.broadcast_to(a, Shape(2, 2, 3)))
print(np.broadcast_to(a.to_numpy(), (2, 2, 3)))
```
```console
[[0.8073 0.5361 0.4442]
[0.9378 0.1910 0.2421]]
2D-array  Shape(2,3)  Strides(3,1)  DType: f64  C-cont: True  F-cont: False  own data: True
[[[0.8073 0.5361 0.4442]
[0.9378 0.1910 0.2421]]
[[0.8073 0.5361 0.4442]
[0.9378 0.1910 0.2421]]]
3D-array  Shape(2,2,3)  Strides(6,3,1)  DType: f64  C-cont: True  F-cont: …
```
> [manipulation routines] Implement` broadcast_to()` for `NDArray`

- numojo/core/ndshape.mojo
This PR aims to add all necessary boundary checks for `NDArrayShape` to ensure a safe use.
- Add boundary checks for `ndim > 0` at initialization.
- Add boundary checks for `shape[i] > 0` at initialization.
- Add complete docstrings for all methods of `Shape` type, e.g., `raises`, `args`, `returns`.
> [shape][safe] Add boundary checks for values of `NDArrayShape` + better docstrings

- numojo/core/ndstrides.mojo
This PR aims to add all necessary boundary checks for `NDArrayStrides` to ensure safe use.
- Add boundary checks for `ndim > 0` at initialization.
- Add complete docstrings for all methods of `Shape` type, e.g., `raises`, `args`, `returns`.
- Chain calling `__init__(shape: NDArrayShape, order: String)` for other list-like shape argument.
- Fix `__eq__` method.
- Add new initialization method to create an uninitialized strides with given length.
> [strides][safe] Add boundary checks for values of `NDArrayStrides` + better docstrings

- numojo/core/ndarray.mojo
- numojo/routines/manipulation.mojo
- numojo/routines/statistics/averages.mojo
- tests/routines/test_statistics.mojo
1. Allow calculating variance and std of an array by axis: `numojo.statistics.variance()` and `numojo.statistics.std()`. 
2. Add corresponding methods for `NDArray`.
3. Add auxiliary function `numojo.manipulation._broadcast_back_to()`.
4. Add tests.
5. Remove un-used imports.
> [statistics] Allow calculating variance and std of an array by axis

- numojo/core/_math_funcs.mojo
- numojo/core/datatypes.mojo
- numojo/core/item.mojo
- numojo/core/ndarray.mojo
- numojo/core/ndshape.mojo
- numojo/core/ndstrides.mojo
- numojo/routines/creation.mojo
- numojo/routines/math/arithmetic.mojo
This PR aims to improve the behaviors of 0-dimensional array (numojo scalar). Note that `a.item(0)` or `a[Item(0)]` is always preferred because the behavior is more determined, but we also allow some ***basic*** operations on 0darray to make users' life easier.
0-dimensional array cannot be constructed by users but can be obtained by array indexing and slicing. Printing this variable gives the scalar and a note that it is an 0darray instead of a mojo scalar. It is similar to `numpy` in that `a[0]` returns a numpy scalar and `a.item(0)` returns a Python scalar. For example,
```
>>> var a = nm.random.arange[f16](0, 3, 0.12)
>>> print(a[1])
0.11999512  (0darray[f16])
>>> print(a.item(1))
0.11999512
>>> var c = nm.array[f16]("[[1,2], [3,4]]")
>>> print(c[1, 1])
4.0  (0darray[f16])
``` …
> [ndarray][doc] Improve behaviors of 0darray + more docstring

- numojo/core/complex/complex_ndarray.mojo
- numojo/core/flags.mojo
- numojo/core/matrix.mojo
- numojo/core/ndarray.mojo
- numojo/core/ndshape.mojo
- numojo/core/ndstrides.mojo
- numojo/core/utility.mojo
- numojo/routines/creation.mojo
- numojo/routines/manipulation.mojo
- numojo/routines/sorting.mojo
- tests/core/test_shape_strides_item.mojo
Adds the `Flags` type for storing information on memory layout. It replaces the current `Dict[String, Bool]` type. The Flags object can also be accessed dictionary-like. Short names are available for convenience. It is similar to `numpy.flags` object. Example:
```mojo
var A = nm.random.rand(2, 3, 4)
print(A.flags.C_CONTIGUOUS)
print(A.flags["C_CONTIGUOUS"])
print(A.flags["C"])
```
They all print `True`.
> [core][flags] Add `Flags` type for storing information on memory layout

- mojoproject.toml
- numojo/core/complex/complex_dtype.mojo
- numojo/core/complex/complex_ndarray.mojo
- numojo/core/complex/complex_simd.mojo
- numojo/core/item.mojo
- numojo/core/matrix.mojo
- numojo/core/ndarray.mojo
- numojo/core/ndshape.mojo
- numojo/core/ndstrides.mojo
- numojo/core/traits/indexer_collection_element.mojo
- numojo/routines/creation.mojo
- numojo/routines/io/files.mojo
- numojo/routines/io/formatting.mojo
- numojo/routines/linalg/decompositions.mojo
- numojo/routines/math/sums.mojo
- numojo/routines/random.mojo
- tests/core/test_matrix.mojo
- tests/science/test_signal.mojo
- tests/utils_for_test.mojo
Updates the code to accommodate to Mojo v25.1. The changes include but are not limited to:
Change constructors.
`str(` -> `String(`
`int(` -> `Int(`
`float(` -> `Float64(`
Change `index()` to `Int()`.
`index(T)` -> `Int(T)`
The function `isdigit()` becomes a method.
`isdigit(a)` -> `a.isdigit()`
Use explicit constructor for complex ndarray.
```mojo
self._re = NDArray[dtype](shape, order)
self._im = NDArray[dtype](shape, order)
```
> [mojo] Update the code to accommodate to Mojo v25.1

- numojo/core/ndarray.mojo
- tests/core/test_array_methods.mojo
Adds `NDAxisIter` struct and `iter_by_axis` method that iterate array by any axis. In each iteration, the iterator yields a 1-d array by specified axis. It is useful when we want to write a universal function to reduce the array by certain axis.
Example:
```mojo
from numojo.prelude import *
var a = nm.arange[i8](24).reshape(Shape(2, 3, 4))
print(a)
for i in a.iter_by_axis(axis=0):
print(String(i))
```
This prints:
```console
[[[ 0  1  2  3]
[ 4  5  6  7]
[ 8  9 10 11]]
[[12 13 14 15]
[16 17 18 19]
[20 21 22 23]]]
3D-array  Shape(2,3,4)  Strides(12,4,1)  DType: i8  C-cont: True  F-cont: False  own data: True
[ 0 12]
[ 1 13]
[ 2 14]
[ 3 15]
[ 4 16]
[ 5 17]
[ 6 18]
[ 7 19]
[ 8 20]
[ 9 21]
[10 22]
[11 23]
```
Another example:
```mojo
from numojo.prelude import *
var a = …
```
> [ndarray] Add `NDAxisIter` struct and `iter_by_axis` method that iterate array by any axis

- numojo/core/ndarray.mojo
- numojo/core/utility.mojo
- numojo/routines/math/extrema.mojo
- numojo/routines/sorting.mojo
- numojo/routines/statistics/averages.mojo
- tests/core/test_array_methods.mojo
- tests/routines/test_statistics.mojo
1. Adds functions that are able to apply any functions working on 1-d array to any axis, with or without dimension reduction.
- Add `apply_func_on_array_with_dim_reduction()` and `apply_func_on_array_without_dim_reduction()`. They try to utilize parallelization as much as possible.
- In future, we only need to focus on writing (and optimizing) functions for 1-d arrays. Operating along certain axis can be easily achieved by applying the function, e.g., `apply_func_on_array_with_dim_reduction[max_1d](array, axis=axis).
3. Implements this approach on functions in statistics.averages module and on the `sort` function. The `sort` function gain speed increase compared to the old method and is quicker than `numpy.sort` for large arrays.
> [routines][generic] Add functionality to allow functions on 1-d array to work on any axis

- .gitignore
- mojoproject.toml
- numojo/core/flags.mojo
- numojo/core/ndarray.mojo
- numojo/core/utility.mojo
- numojo/routines/manipulation.mojo
- numojo/routines/random.mojo
- numojo/routines/sorting.mojo
- numojo/routines/statistics/averages.mojo
- tests/routines/test_manipulation.mojo
- tests/routines/test_sorting.mojo
1. Refine `argsort` function by applying the universal function. Improve the speed significantly (see below). Also, it fixes the problem that `argsort` does not work for F-order array.
2. Improve the speed of `sort` for 1d-array by adding partition functions which do not construct the indices array.
3. Update `_NDAxisIter` to allow order argument.
4. Re-write `ravel` function by means of `_NDAxisIter`, so that it will not break for F-order arrays.
5. Add many tests for the functions, to allow C or F operations both C and F arrays (4 different scenarios).
6. Add `FORC` attribute for the `Flags` type.
`argsort` numojo vs numpy:
```console
100000000 1-d array.
numojo 8.672953000001144
numpy 11.353579999995418
10_000 * 10_000 2-d array sorted by axis 0.
numojo 1.9524170000222512
numpy …
```
> [sorting][core] Refine `argsort`, `sort`, `ravel`, and `_NDAxisIter`

- .gitignore
- numojo/core/ndarray.mojo
- numojo/routines/io/formatting.mojo
This PR changes the approach in determining the min and max values of the printable regions of an array. This significantly improves the speed of printing arrays.
This improvement is particularly significant when we encounter very large arrays. The speed increase can be x100000. See the following comparison on a (10000, 1000) array.
```console
2D-array  Shape(10000,1000)  Strides(1000,1)  DType: f64  C-cont: True  F-cont: False  own data: True
Time to print array: 19.190531999978703
2D-array  Shape(10000,1000)  Strides(1000,1)  DType: f64  C-cont: True  F-cont: False  own data: True
Time to print array: 0.0001010000123642385
```
> [core][print] Significantly increase the speed of printing arrays

- numojo/__init__.mojo
- numojo/core/complex/complex_ndarray.mojo
- numojo/core/ndarray.mojo
- numojo/routines/linalg/__init__.mojo
- numojo/routines/linalg/misc.mojo
- numojo/routines/sorting.mojo
- tests/routines/test_linalg.mojo
- tests/routines/test_sorting.mojo
This PR:
- Implements the `diagonal` function in `linalg.misc` module. Also includes it in the NDArray as a method. Add tests for it.
- Fix the `NDArray.sort()` method (in-place sort). The default axis is -1 rather than None. Add tests for it.
> [diagonal][sort] Add `diagonal` function + fix `NDArray.sort()` method

- docs/features.md
- numojo/core/item.mojo
- numojo/core/ndarray.mojo
- numojo/core/ndshape.mojo
- numojo/core/ndstrides.mojo
- numojo/routines/__init__.mojo
- numojo/routines/functional.mojo
- numojo/routines/indexing.mojo
- tests/core/test_array_methods.mojo
- Improve `_NDIter` to allow arbitrary axis to travel.
- Add method `ith()` to get the i-th item of the iterator.
- Add `swapaxes()` for shape and strides.
- Add `offset()` for `Item` type to get offset.
- Constructor for `Item` from index and shape.
- Add tests for C or F array with `nditer` from C or F orders.
> [core] Improve `NDIter` to allow arbitrary axis to travel

- README.MD
- docs/changelog.md
> [doc][changelog] Change log for the release v0.6

- numojo/__init__.mojo
- numojo/routines/indexing.mojo
- tests/routines/test_indexing.mojo
This will:
1. Implemented `take_along_axis` function in `numojo/routines/indexing.mojo`:
- Takes values from an input array along a specified axis based on indices
- Handles arrays of any dimension with axis specification
- Supports broadcasting of indices when shapes don't exactly match
- Includes proper error handling for invalid inputs
2. Created comprehensive test suite in `tests/routines/test_indexing.mojo`:
- Tests for arrays of different dimensions (1D, 2D, 3D)
- Tests with various axis specifications (positive, negative indices)
- Tests with different index types (int32, int64)
- Verification against NumPy's implementation for correctness
> [routines] Implement `take_along_axis` method

- .gitignore
- mojoproject.toml
- numojo/__init__.mojo
- numojo/core/complex/complex_ndarray.mojo
- numojo/routines/indexing.mojo
- numojo/routines/io/__init__.mojo
- numojo/routines/io/formatting.mojo
- tests/routines/test_indexing.mojo
Merge the commit on hotfix from main to pre-0.7
> [repo] Merge hotfix from main to pre-0.7

- mojoproject.toml
- numojo/core/ndarray.mojo
- numojo/routines/functional.mojo
- numojo/routines/math/extrema.mojo
- numojo/routines/searching.mojo
- tests/routines/test_searching.mojo
- tests/utils_for_test.mojo
This pull request focuses on enhancing the functionality of the `NDArray` class and improving the `argmax` and `argmin` methods. Additionally, new tests have been added to ensure the correctness of these methods.
Improvements to `argmax` and `argmin` methods:
* `numojo/routines/searching.mojo`: Introduced new `argmax` and `argmin` functions that handle both 1D and multi-dimensional arrays. These functions now support axis-based operations and include detailed documentation and examples.
* `numojo/routines/functional.mojo`: Added overloads of `apply_along_axis` to support the new `argmax` and `argmin` functions, ensuring they reduce the dimension of the input array appropriately.
Enhancements to `NDArray` class:
* `numojo/core/ndarray.mojo`: The `argmax` and `argmin` methods have been …
> [routines] Re-write `argmax` and `argmin` to returns indices along the given axis

- numojo/routines/linalg/decompositions.mojo
- tests/core/test_matrix.mojo
This PR optimizes the QR decomposition utilizing configurable memory layouts and SIMD. When the input matrix is detected to be in row-major (C) layout, it is reordered to column-major (F) layout before performing Householder transformations. After factorization, the final Q and R are reordered to the original layout of the input Matrix, preserving consistency for downstream operations.  For an input matrix with column-major (F) layout, no reordering is needed.
**Changes**  
1. **Vectorized Householder Transformations**  
Updated algorithm leverages SIMD with calls to `vectorize` for computing and applying Householder reflections.  
2. **Reduced and Complete Modes**  
Adds support for both “reduced” and “complete” modes, similar to NumPy’s QR.  For an input Matrix A with shape (m,n):
- …
> [routines] Optimized QR Decomposition with SIMD and Column-Major Layout

- .github/workflows/run_tests.yaml
- numojo/core/matrix.mojo
- numojo/routines/linalg/decompositions.mojo
- numojo/routines/linalg/products.mojo
- numojo/routines/linalg/solving.mojo
- numojo/routines/manipulation.mojo
- numojo/routines/math/extrema.mojo
- numojo/routines/math/products.mojo
- numojo/routines/math/sums.mojo
- numojo/routines/searching.mojo
- numojo/routines/sorting.mojo
- tests/core/test_matrix.mojo
This PR enhances Matrix with support for both C-contiguous (row-major) and F-contiguous (column-major) memory layouts across all matrix routines. Default memory layout remains C-contiguous to keep API close to NumPy. Matrix tests are performed for both memory layouts.
- Add conditional compilation flag `F_CONTIGUOUS` to control matrix memory layout in tests
- Modify GitHub workflow to run test suite with both layouts:
- Additional test run for matrix tests with [flag](https://docs.modular.com/mojo/cli/test/#-d-keyvalue) `-D F_CONTIGUOUS`
- Matmul handles all memory layout combinations with specialized implementations.
> [Matrix][routines] Add Column-Major Memory Layout Support Across All Matrix Routines

- numojo/core/matrix.mojo
- numojo/routines/linalg/__init__.mojo
- numojo/routines/linalg/decompositions.mojo
- numojo/routines/linalg/misc.mojo
- tests/core/test_matrix.mojo
This PR adds eigenvalue decomposition for real symmetric matrices using the QR algorithm. 
- Added `eig()` function that returns a  A tuple `(Q, D)` where:
- Q: A matrix whose columns are the eigenvectors
- D: A diagonal matrix containing the eigenvalues
- Added `issymmetric()` helper function to verify matrix symmetry
>  [Matrix][decompositions] Add Eigenvalue Decomposition for Symmetric Matrices 

- numojo/core/ndarray.mojo
- numojo/routines/functional.mojo
- numojo/routines/sorting.mojo
- tests/routines/test_sorting.mojo
This PR:
- Add stable sort to the function `sort()`. Users can use the argument `stable` to make a stable sort.
- Re-write the in-place sort (instable and stable) using the `apply_long_axis()` function, so that we do not need to several transposes.
- Add an override for `apply_long_axis()`, which apply the function in-place.
> [routines] Add stable sort and re-write in-place sort
