Mojo-Numerics-and-Algorithms-group/NuMojo

ndarray/array2d.mojo

Adding full array reduce functions.

added: sum, prod, min, avg, and max to array2d

---

numojo/traits/__init__.mojo

fix traits submodule not having an init

---

README.MD
gitignore

Fix a typo in example code in readme file  (`tensor` instead of `Tensor`).
Add __init__ to base module for importing.
Add gitignore file.

Fix a typo in example code in readme file. Add __init__ to base module. Add gitignore file.

---

ind_to_slice.mojo
numojo/core/datatypes.mojo
numojo/core/ndarray.mojo
numojo/core/ndarrayview.mojo
numojo/core/random.mojo

Rewrote reshape() using new methods and fixed the error coming from `if` condition in `__getitem__`. 
Reshaping should work fine now.

Fixed the problem in reshape and __getitem__

---

numojo/core/ndarray.mojo
numojo/core/utility_funcs.mojo

- added some functions without axis parameter such as flatten, as type, argmin, argmax, any, all. 
- Fixed a bug that that prevents slicing an array when the resultant array is just one element.

More function in NDArray, Fixed Bugs

---

CONTRIBUTING.md
README.MD
Roadmap.md

Textual changes to the readme and use another example.

[doc] Textual changes to the readme and use another example

---

numojo/core/ndarray.mojo
numojo/core/ndarray_utils.mojo

- matmul_parallelized_simd has been removed to prevent redundancy.
- to_numpy() has been fixed and works now.

Fixes & removals

---

.gitignore
numojo/core/ndarray.mojo
tests/get_item_by_index.mojo

This PR resolves Effort 1(b) of #68. It allows users to get items by List[Int] or NDArray[DType.index]. It now returns a non-flattened array. The behavior is aligned with numpy, which returns an array that has the same ndim with the input array, but only differs in the shape of the first dimension. See examples below.
Example:
```console
> var A = nm.NDArray[nm.i8](3,random=True)
> print(A)
[       14      97      -59     ]
1-D array  Shape: [3]  DType: int8
>
> print(A[List[Int](2,1,0,1,2)])
[       -59     97      14      97      -59     ]
1-D array  Shape: [5]  DType: int8
>
> var B = nm.NDArray[nm.i8](3, 3,random=True)
> print(B)
[[      -4      112     -94     ]
[      -48     -40     66      ]
[      -2      -94     -18     ]]
2-D array  Shape: [3, 3]  DType: int8
>
> …
```

[lib+test+doc] Get item by List[Int] or NDArray[DType.index]

---

README.MD
numojo/core/ndarray.mojo

Change default type of NDArray to nm.f64
Add Discord link to the readme.

[lib+doc] Change default type of NDArray to nm.f64

---

magic.lock
numojo/math/linalg/__init__.mojo
numojo/math/linalg/solve.mojo
numojo/math/linalg/solver.mojo
tests/test_array_manipulation.mojo
tests/test_math.mojo

Add `solve` function for linear algebra `AX = Y`.

[Add] `solve` function for linear algebra `AX = Y`

---

mojoproject.toml
numojo/core/ndarray.mojo
tests/test_math.mojo

Minor fixes in .toml file to work with max/mojo v24.5

updated .toml to use max/mojo24.5

---

mojoproject.toml

Update toml (case sensitive)

---

.github/workflows/run_tests.yaml

[update] update the test flow file to accommodate 24.5 and MAGIC.

[update] update the test flow file to accommodate 24.5 and MAGIC

---

README.MD
docs/readme_zhs.md
docs/readme_zht.md

[doc] Add readme for traditional Chinese and update the readme file.

[doc] Add readme for traditional Chinese and update the readme file

---

.github/workflows/run_tests.yaml
.github/workflows/test_pre_commit.yaml

Reverts Mojo-Numerics-and-Algorithms-group/NuMojo#121
Was using premagic versoion yaml

Revert "Switch github runner to ubuntu-22.04"

---

.github/workflows/run_tests.yaml
.github/workflows/test_pre_commit.yaml

Now with magic version of tests

---

numojo/prelude.mojo

[change] Add `Idx` and `NDArrayShape` to `prelude`

---

README.MD
docs/readme_zhs.md
docs/readme_zht.md

Add changelog into readme file

---

numojo/core/ndarray.mojo

This PR covers a minor correction to getter and setter functions, specifically the `_adjust_slice`.

Fixed adjust slice 

---

magic.lock
mojoproject.toml
numojo/math/__init__.mojo
numojo/math/signal/__init__.mojo
numojo/math/signal/signal.mojo
tests/test_signal.mojo

Add `convolve2d` function and the `signal` module.
It has the similar objective as the `scipy.signal` module.

[add] Add `convolve2d` function in the `signal` module

---

README.MD
docs/features.md

Update the `readme.md` and `features.md` to reflect current progress.

[doc] Update the `readme.md` and `features.md` to reflect current progress

---

numojo/core/ndarray.mojo

1. Update `item` method to separate the cases when input is an Int it is *Int.
2. Allow negative index and conduct boundary checks on that.
3. Some clean-ups.

[update][core] Update `item` method

---

numojo/__init__.mojo

Set `__version__` to correct V0.4

Update __version__ in __init__.mojo

---

numojo/__init__.mojo
numojo/core/ndarray.mojo
numojo/routines/math/__init__.mojo
numojo/routines/math/arithmetic.mojo
numojo/routines/math/misc.mojo
tests/routines/test_math.mojo

Implement `clip()` function for scalar a_min and a_max in `math.misc` module. Add corresponding method in `NDArray`. Add tests.

[routines] Implement `clip()` function

---

numojo/core/complex/complex_ndarray.mojo
numojo/core/ndarray.mojo
numojo/routines/creation.mojo
tests/core/test_complexArray.mojo

- This PR aims to improve the existing ComplexNDArray getter methods by aligning with the methods currently implemented in the NDArray. 
- It's the first step towards standardizing ComplexNDArray methods to match those of NDArray to provide seamless transition between the two and to lay the foundation for the upcoming FFT module PR.

[core][complex ndarray] Improve ComplexNDArray getter methods

---

.github/workflows/run_tests.yaml
.pre-commit-config.yaml
numojo/core/complex/complex_ndarray.mojo
numojo/core/ndarray.mojo
numojo/routines/creation.mojo
numojo/routines/manipulation.mojo
numojo/routines/math/differences.mojo

This pull request includes several changes across workflows, pre-commit configurations, and multiple files in the `numojo` library. The changes focus on simplifying code formatting, improving workflows, and enhancing maintainability by removing unnecessary parentheses and restructuring code for better readability.

[workflow][format] Fix the linting issues and update the work flow
